# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_amount',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
